name: Build and Push Docker Image

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: Tessian-Task

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUBTOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUBUSERNAME }}/$IMAGE_NAME .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUBUSERNAME }}/$IMAGE_NAME
